language: bash

services:
- docker

env:
- BASE_IMAGE_STABILITY_TAG=4.12.9
- ADMINER_VER=4.7.3 ADMINER_LANG=en TAGS=4.7,4,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
