language: bash

services:
  - docker

env:
  - BASE_IMAGE_STABILITY_TAG=4.11.9
  - GIT_MERGE_SEPARATOR_DUMMY_ENV_VAR=1
  - ADMINER_VER=4.7.1 ADMINER_LANG=en TAGS=4.7,4,latest

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
